Update README.md
devrelcollective/awesome-devrel pull request #60
Opened 2022-09-05 08:33 UTC by shrirajpawar4

2022-09-12 09:54 UTC, RCheesley approved these changes

2023-01-25 16:03 UTC, RCheesley requested changes
Small suggestion, thanks for the PR!

2023-01-25 16:03 UTC, RCheesley commented on README.md
> +* [CommonRoom](https://www.commonroom.io/) - community growth platform
```suggestion
* [CommonRoom](https://www.commonroom.io/): Community growth platform
```

To keep in line with the formatting of other comments as above.

2023-02-03 19:26 UTC, hhkaos commented
I have found another alternative: https://www.crowd.dev/ 😄

2023-10-18 15:08 UTC, merged